# Generated by Django 5.2.1 on 2025-06-03 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="name",
            field=models.CharField(default=5, max_length=100),
            preserve_default=False,
        ),
    ]
