# Generated by Django 5.1.6 on 2025-03-12 20:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_bookings_phone_number_doctor_created_at_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bookings',
            old_name='patient',
            new_name='user',
        ),
    ]
